"""
@file patient.py

@brief Defines the patient models used throughout the VitaSync
application.

@details
Provides the primary patient models responsible for representing patient
information within the VitaSync system.

This module includes:

- the MedicalCondition enumeration, representing the supported clinical
  conditions that may be associated with a patient;
- the Patient model, which stores complete patient information;
- the PatientCreate model, which represents the information required when
  creating a new patient record.

These models perform validation and normalization of patient data,
maintain consistency with associated ABHA KYC information where
available, and ensure that all patient records satisfy the application's
business rules before being persisted.
"""

from datetime import datetime, date
import re
from enum import StrEnum, auto
from pydantic import (
    BaseModel,
    Field,
    field_validator,
    model_validator,
    ConfigDict
)

from vitasync.models.ABHA.kyc import ABHAKYC
from vitasync.common.converter import concatenate_name
from vitasync.common.idgenerator import PatientID
import vitasync.common.validator as validator


# ──────────────────────────────────────────────────────────────────────────────
# Medical Condition Enumeration
# ──────────────────────────────────────────────────────────────────────────────

class MedicalCondition(StrEnum):
    """
    @brief Enumerates the medical conditions supported by VitaSync.

    @details
    Defines the standardized collection of medical conditions that may be
    associated with a patient's medical record.

    The enumeration is organized into logical clinical categories,
    including obstetric, gynaecological, neonatal, and chronic medical
    conditions. These values are used consistently throughout the
    application for patient creation, updates, filtering, and querying.
    """

    # Obstetric Conditions
    PREGNANCY = auto()
    HIGH_RISK_PREGNANCY = auto()
    GESTATIONAL_DIABETES = auto()
    PREECLAMPSIA = auto()
    ECLAMPSIA = auto()
    PLACENTA_PREVIA = auto()
    PLACENTAL_ABRUPTION = auto()
    PRETERM_LABOR = auto()
    POSTPARTUM_HEMORRHAGE = auto()
    ECTOPIC_PREGNANCY = auto()
    MISCARRIAGE = auto()
    STILLBIRTH = auto()
    MULTIPLE_GESTATION = auto()        # Twins, triplets, and other multiple pregnancies.
    HYPEREMESIS_GRAVIDARUM = auto()    # Severe pregnancy-related nausea and vomiting.

    # Gynaecological Conditions
    POLYCYSTIC_OVARY_SYNDROME = auto()
    ENDOMETRIOSIS = auto()
    UTERINE_FIBROIDS = auto()
    CERVICAL_DYSPLASIA = auto()
    OVARIAN_CYST = auto()
    PELVIC_INFLAMMATORY_DISEASE = auto()
    VULVODYNIA = auto()
    MENORRHAGIA = auto()               # Heavy menstrual bleeding.
    AMENORRHEA = auto()                # Absence of menstruation.
    DYSMENORRHEA = auto()              # Painful menstruation.

    # Neonatal Conditions
    NEONATAL_JAUNDICE = auto()
    NEONATAL_SEPSIS = auto()
    LOW_BIRTH_WEIGHT = auto()
    RESPIRATORY_DISTRESS_SYNDROME = auto()
    NEONATAL_HYPOGLYCEMIA = auto()
    CONGENITAL_HEART_DEFECT = auto()

    # Chronic / Comorbid Conditions
    HYPERTENSION = auto()
    DIABETES_MELLITUS = auto()
    ANEMIA = auto()
    HYPOTHYROIDISM = auto()
    HYPERTHYROIDISM = auto()
    ASTHMA = auto()
    EPILEPSY = auto()
    DEPRESSION = auto()
    ANXIETY = auto()
    HIV = auto()
    HEPATITIS_B = auto()
    TUBERCULOSIS = auto()


# ──────────────────────────────────────────────────────────────────────────────
# Patient Model
# ──────────────────────────────────────────────────────────────────────────────

class Patient(BaseModel):
    """
    @brief Represents a patient registered within the VitaSync system.

    @details
    Stores the complete patient record, including the patient's unique
    identifier, demographic information, medical conditions, ABHA KYC
    information, activity status, and record creation timestamp.

    The model performs comprehensive validation and normalization to
    ensure that manually supplied patient information remains consistent
    with associated ABHA KYC information whenever such information is
    available.

    Missing information such as the patient's name, mobile number, or
    date of birth may be automatically populated from the linked ABHA KYC
    record where appropriate.
    """

    model_config = ConfigDict(populate_by_name=True)

    pid: str = Field(
        ...,
        serialization_alias='patientID',
        validation_alias='patientID',
        description='The unique patient identifier generated by the VitaSync patient identifier generator.'
    )

    name: str = Field(
        '',
        serialization_alias='patientName',
        validation_alias='patientName',
        description='The patient\'s full legal name.'
    )

    mobile_number: str = Field(
        '',
        serialization_alias='mobileNumber',
        validation_alias='mobileNumber',
        description='The patient\'s primary registered mobile number.'
    )

    date_of_birth: datetime | None = Field(
        None,
        serialization_alias='dob',
        validation_alias='dob',
        description='The patient\'s date of birth.'
    )

    conditions: set[MedicalCondition] = Field(
        default_factory=set,
        serialization_alias='medicalConditions',
        validation_alias='medicalConditions',
        description='The collection of medical conditions currently associated with the patient.'
    )

    is_active: bool = Field(
        True,
        serialization_alias='isActive',
        validation_alias='isActive',
        description='Indicates whether the patient record is currently active within the VitaSync system.'
    )

    abha_kyc: ABHAKYC | None = Field(
        None,
        serialization_alias='abhaKYC',
        validation_alias='abhaKYC',
        description='The patient\'s associated ABHA Know Your Customer (KYC) information, if available.'
    )

    created_on: datetime = Field(
        default_factory=datetime.now,
        serialization_alias='createdOn',
        validation_alias='createdOn',
        description='The timestamp at which the patient record was created.'
    )

    @field_validator('pid')
    @classmethod
    def validate_patient_id(cls, v):
        """
        @brief Validates a VitaSync patient identifier.

        @details
        Delegates validation of the supplied patient identifier to the
        centralized PatientID validator, ensuring that all patient
        identifiers conform to the application's expected format.

        @param v
            The supplied patient identifier.

        @return
            The validated patient identifier.

        @throws ValueError
            If the supplied patient identifier is invalid.
        """
        return PatientID.validate(v)

    @model_validator(mode='after')
    def validate_model(self) -> 'Patient':
        """
        @brief Performs cross-field validation and normalization.

        @details
        Validates relationships between multiple fields after individual
        field validation has completed.

        Missing information is automatically populated from the patient's
        ABHA KYC record whenever possible, and manually supplied values
        are verified for consistency against the corresponding ABHA
        demographic information.

        Specifically, this validator:

        - derives the patient's name from ABHA KYC when necessary;
        - validates and normalizes the patient's name;
        - derives the patient's mobile number from ABHA KYC when
          necessary;
        - validates the patient's mobile number;
        - derives the patient's date of birth from ABHA KYC when
          necessary;
        - verifies consistency between manually supplied values and the
          patient's ABHA demographic information.

        @return
            The validated and normalized Patient model.

        @throws ValueError
            If any cross-field validation rule is violated.
        """

        # -----------------------------------------------------------------
        # Validate and normalize the patient's name.
        # -----------------------------------------------------------------
                # If no name was supplied manually, attempt to derive it from the
        # patient's ABHA demographic information.
        if not self.name:
            if self.abha_kyc is None:
                raise ValueError('No name given to Patient, no ABHA KYC present to fetch the name.')

            self.name = concatenate_name(
                self.abha_kyc.demographic_data.first_name,
                self.abha_kyc.demographic_data.middle_name,
                self.abha_kyc.demographic_data.last_name
            )

        # Ensure that the patient's name does not contain numeric
        # characters.
        if re.search(r'\d', self.name) is not None:
            raise ValueError('Name given to Patient contains digits.')

        # Normalize the patient's name into title case.
        self.name = self.name.title()

        # If ABHA KYC information is available, verify that the manually
        # supplied name remains consistent with the verified demographic
        # information.
        if self.abha_kyc is not None:
            if self.abha_kyc.demographic_data.first_name not in self.name:
                raise ValueError('First name given in ABHA KYC does not match with the name given manually.')

            # If the manually supplied name omits the verified last name,
            # reconstruct the complete name using the ABHA demographic
            # information.
            if (
                self.abha_kyc.demographic_data.last_name and
                self.abha_kyc.demographic_data.last_name not in self.name
            ):
                self.name = concatenate_name(
                    self.abha_kyc.demographic_data.first_name,
                    self.abha_kyc.demographic_data.middle_name,
                    self.abha_kyc.demographic_data.last_name
                )

        # -----------------------------------------------------------------
        # Validate and normalize the patient's registered mobile number.
        # -----------------------------------------------------------------

        # If no mobile number was supplied manually, attempt to obtain it
        # from the patient's ABHA demographic information.
        if not self.mobile_number:
            if self.abha_kyc is None:
                raise ValueError('No mobile number given to Patient, no ABHA KYC present to fetch the number.')

            self.mobile_number = self.abha_kyc.demographic_data.mobile_number

        # Normalize the supplied mobile number by removing supported Indian
        # dialing prefixes before validating its format.
        cleaned = re.sub(r'^(\+91|0)', '', self.mobile_number.strip())

        if not cleaned.isdigit() or len(cleaned) != 10:
            raise ValueError('Mobile number given for Patient is invalid.')

        # -----------------------------------------------------------------
        # Validate and normalize the patient's date of birth.
        # -----------------------------------------------------------------

        # If no date of birth was supplied manually, attempt to obtain it
        # from the patient's ABHA demographic information.
        if self.date_of_birth is None:
            if self.abha_kyc is None:
                raise ValueError('Cannot fetch date of birth automatically from ABHA KYC as no KYC was given. Input date of birth manually.')

            self.date_of_birth = self.abha_kyc.demographic_data.date_of_birth

        # Verify that the manually supplied date of birth matches the
        # verified ABHA demographic information.
        if self.abha_kyc is not None:
            if self.date_of_birth != self.abha_kyc.demographic_data.date_of_birth:
                raise ValueError('Manually inputted date of birth and date of birth given in ABHA KYC does not match.')

        return self

    @property
    def abha_name(self) -> str | None:
        """
        @brief Returns the patient's full name from their ABHA KYC record.

        @details
        Constructs and returns the patient's complete legal name using the
        demographic information stored within the associated ABHA KYC
        record.

        @return
            The patient's full name from the ABHA KYC record if one is
            associated with the patient; otherwise None.
        """
        return concatenate_name(
            self.abha_kyc.demographic_data.first_name,
            self.abha_kyc.demographic_data.middle_name,
            self.abha_kyc.demographic_data.last_name
        ) if self.abha_kyc is not None else None

    @property
    def abha_dob(self) -> date | None:
        """
        @brief Returns the patient's date of birth from their ABHA KYC
        record.

        @details
        Retrieves the verified date of birth stored within the patient's
        associated ABHA demographic information.

        @return
            The patient's verified ABHA date of birth if ABHA KYC
            information is available; otherwise None.
        """
        return self.abha_kyc.demographic_data.date_of_birth if self.abha_kyc is not None else None

    def sync_mobile_number_with_abha(self) -> bool:
        """
        @brief Synchronizes the patient's mobile number with ABHA.

        @details
        Updates the patient's registered mobile number using the mobile
        number stored within the associated ABHA demographic information.

        No synchronization is performed if the patient does not have an
        associated ABHA KYC record.

        @return
            True if synchronization was successfully performed;
            otherwise False.
        """
        if self.abha_kyc is None:
            return False

        # Synchronize the patient's registered mobile number with the
        # verified mobile number stored in the ABHA demographic
        # information.
        self.mobile_number = self.abha_kyc.demographic_data.mobile_number

        return True


# ──────────────────────────────────────────────────────────────────────────────
# Patient Creation Model
# ──────────────────────────────────────────────────────────────────────────────

class PatientCreate(BaseModel):
    """
    @brief Represents the information required to create a new patient.

    @details
    Stores the information supplied when registering a new patient before
    a permanent patient identifier and creation timestamp have been
    assigned.

    The model validates and normalizes user-supplied information prior to
    its conversion into a complete Patient instance by the PatientManager.
    """

    model_config = ConfigDict(populate_by_name=True)

    name: str = Field(
        default='',
        serialization_alias='patientName',
        validation_alias='patientName',
        description='The patient\'s full legal name.'
    )

    mobile_number: str = Field(
        '',
        serialization_alias='mobileNumber',
        validation_alias='mobileNumber',
        description='The patient\'s primary registered mobile number.'
    )

    date_of_birth: datetime | None = Field(
        None,
        serialization_alias='dob',
        validation_alias='dob',
        description='The patient\'s date of birth.'
    )

    conditions: set[MedicalCondition] = Field(
        default_factory=set,
        serialization_alias='medicalConditions',
        validation_alias='medicalConditions',
        description='The collection of medical conditions currently associated with the patient.'
    )

    is_active: bool = Field(
        True,
        serialization_alias='isActive',
        validation_alias='isActive',
        description='Indicates whether the patient record should initially be marked as active.'
    )

    @field_validator('mobile_number')
    @classmethod
    def validate_mobile_number(cls, v):
        """
        @brief Validates the patient's mobile number.

        @details
        Delegates validation of the supplied mobile number to the shared
        application validator, ensuring that the number conforms to the
        expected Indian mobile number format before a patient record is
        created.

        @param v
            The supplied mobile number.

        @return
            The validated and normalized mobile number.

        @throws ValueError
            If the supplied mobile number is invalid.
        """
        return validator.validate_mobile_number(v)

    @field_validator('date_of_birth')
    @classmethod
    def validate_date_of_birth(cls, v):
        """
        @brief Validates the patient's date of birth.

        @details
        Delegates validation of the supplied date of birth to the shared
        application validator.

        Validation ensures that the supplied value represents a valid
        historical date and performs any normalization required by the
        application before the model is created.

        @param v
            The supplied date of birth.

        @return
            The validated and normalized date of birth.

        @throws ValueError
            If the supplied date of birth is invalid.
        """
        return validator.validate_date_of_birth(v)
